CONTRIBUTING.md
README.md
__tests__/setup-beam.test.js
dist/index.js
dist/install-elixir
dist/install-otp
package-lock.json
package.json
src/install-elixir
src/install-otp
src/installer.js
src/setup-beam.js

This PR touches all files where we had `setup-elixir` but is now renamed to `setup-beam`. 
Edit:
Closes #20

Rename to setup-beam

---

.eslintrc.yml
.prettierrc
3RD_PARTY_LICENSES
__tests__/setup-beam.test.js
dist/index.js
package-lock.json
package.json
src/installer.js
src/setup-beam.js

So, after the previous experience with #9 I thought we could further restrict the JavaScript code by making for stricter linting. This pull request presents that.
How it rolled:
1. I moved from `google` to `airbnb` (https://github.com/erlef/setup-beam/actions/runs/702116828)
2. I ran the CI command and started _fixing_ stuff
(this actually came from a comment by Eric where he asked if `return await` was OK - I thought "if it isn't there's probably some linting, out there, that'll help us further")

Apply stricter linting

---

.github/workflows/test.yml
3RD_PARTY_LICENSES
__tests__/setup-beam.test.js
dist/index.js
src/setup-beam.js

This is an attempt at trying to understand why OTP 24 is not available yet. Opening as a draft as most likely this investigation will result is a closed-unmerged branch.

Fix version ranges for non-semver

---

dist/index.js
src/setup-beam.js

Before this patch we printed:
Using Elixir / -otp- version v1.12.0-otp-24
The ` / -otp-` part looks a bit out of place.
After this patch, it is simply:
Using Elixir v1.12.0-otp-24

Change how we print installed Elixir version

---

.github/workflows/ci.yml
.github/workflows/test.yml
__tests__/setup-beam.test.js
dist/index.js
src/setup-beam.js

Closes #40.
Also closes #39.
**Edit**: after this one's approved and merged we could think about 1.7.2, since there's also a recent patch by @wojtekmach in the queue.

Allow for latest 100 rebar3 versions when fetching from GitHub

---

.github/workflows/ubuntu.yml
__tests__/setup-beam.test.js
dist/index.js
src/setup-beam.js

Closes #60 
This commit conditionally prepends `v` on an elixir version. Specifically, when the elixir version starts with digit, we prepend `v`, otherwise we leave it as is.

Don't preprend v when elixir version does not start with digits

---

dist/index.js
src/setup-beam.js

We output the variable's value to ease debugging around this issue.
Ref.: https://github.com/erlef/setup-beam/issues/58#issuecomment-886125419

Ease debugging around ImageOS env.var

---

README.md

Otherwise it is difficult to know that the erlef/setup-beam matchers are what is creating the warning/error annotations on PR's

Mention what problem matchers do in the README

---

README.md
action.yml
dist/index.js
src/setup-beam.js

Closes #77.
@hauleth, let me know if this change is good for you, as is. It's not `enable_`, since that was the default, but it serves the same purpose.

Allow disabling problem matchers

---

.github/workflows/update_3rd_party_licenses.sh
.github/workflows/update_3rd_party_licenses.yml

Instead of pushing directly, since the `main` branch is protected, this creates a pull request.
Failure: https://github.com/erlef/setup-beam/actions/runs/1852644324
It's possible this pull request doesn't pass CI since the 3rd party licenses are outdated, but once it's accepted+merged in at most 24h stuff should be back to normal.

Fix 3rd party license updater (automation)

---

.github/workflows/ubuntu.yml
.github/workflows/windows.yml
README.md
dist/index.js
dist/install-elixir.ps1
dist/install-elixir.sh
dist/install-gleam.ps1
dist/install-gleam.sh
dist/install-otp.ps1
dist/install-otp.sh
dist/install-rebar3.ps1
dist/install-rebar3.sh
src/install-elixir.ps1
src/install-elixir.sh
src/install-gleam.ps1
src/install-gleam.sh
src/install-otp.ps1
src/install-otp.sh
src/install-rebar3.ps1
src/install-rebar3.sh
src/setup-beam.js

⚠️ don't merge before #91+#92 and the 3rd party licenses are update (lest we have "expected" errors which don't tell the whole story)
This introduces some env. variables to the run, namely the ones identified in the `README.md`:
- `INSTALL_DIR_FOR_ELIXIR`: base folder for Erlang/OTP
- `INSTALL_DIR_FOR_GLEAM`: base folder for Elixir
- `INSTALL_DIR_FOR_OTP`: base folder for Gleam
- `INSTALL_DIR_FOR_REBAR3`: base folder for `rebar3`
and hopefully it closes #89 (still waiting on a comment/test by @samaaron)

Add environment variables

---

.github/workflows/ubuntu.yml
.github/workflows/windows.yml

⚠️ don't merge before #91+#92 and the 3rd party licenses are update (lest we have "expected" errors which don't tell the whole story)
Checking how this all behaves with `25.0-rc1`.

Attempt use on top of Erlang 25.0-rc1

---

.github/workflows/action.yml
dist/index.js
src/setup-beam.js

This hopefully fixes one of the issues found via #99 (mis-handling of booleans).
**Note**: this'll most likely break stuff in-the-wild, since the way the values were being read (`getInput`) meant we'd always mix `rebar` and `hex`. We can either go with this approach (and bump major) or consider the default should've been `true`, from the start, and change that.

Handle strings as such

---

package-lock.json
package.json

I actually [went to the developer first](https://github.com/rasshofer/yaml-lint/issues/28#issuecomment-1106880768), pull requested the lib., but then [my update got rejected](https://github.com/rasshofer/yaml-lint/pull/30), since the lib. [moved to TypeScript (from JavaScript)](https://github.com/rasshofer/yaml-lint/issues/28#issuecomment-1106893662); still, a [new release](https://github.com/rasshofer/yaml-lint/releases/tag/v1.3.0) was done and this might just solve our issue.

Apply security fix as proposed by Dependabot

---

README.md

Fixes typos in the description of environment variables in the project's README.md file.

Fix wrong environment variable descriptions in the README

---

README.md

I seem to have introduced it in https://github.com/erlef/setup-beam/pull/81/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R21 so it's only fair (and less embarrassing for me) that I fix it :)

Fix mispaste in README.md

---

dist/index.js
src/setup-beam.js

Don't take `maint-` -prefixed versions into account unless they're asked for it specifically.
At the same time, while fetching versions, make sure we identify them better so that `25` does not end up pulling `maint-25` instead of `OTP-25.0`, as it should.
Closes #120.

Wrong Erlang/OTP version `maint-x` matched when requesting `x`

---

dist/index.js
dist/install-otp.ps1
dist/install-otp.sh
src/install-otp.ps1
src/install-otp.sh
src/setup-beam.js

It is especially useful not to install things globally on self-hosted runner as these may not be running in isolation.
By installing OTP into a known location we could remove the code that was checking where exactly it was installed.
This PR also removes the `echo $INSTALL_DIR_FOR_OTP >> $GITHUB_ENV` (and the PowerShell equivalent) as it never worked. The variable name should have been `$GITHUB_PATH`, not `$GITHUB_ENV`. Again, no longer necessary as we install OTP to a known location.

Install OTP on Windows to a local directory

---

.github/workflows/ubuntu.yml
__tests__/setup-beam.test.js
dist/index.js
src/setup-beam.js

Closes #131.
**Edit**: this also fixes some tests that started failing due to our new pre-conditions.

Crash on invalid Elixir+OTP combo

---

dist/install-otp.ps1
dist/install-otp.sh
src/install-otp.ps1
src/install-otp.sh

Ref: https://github.com/erlef/setup-beam/pull/139#discussion_r970967071
Before: (See "List environment variables" step)
- Ubuntu: https://github.com/erlef/setup-beam/actions/runs/3043092234/jobs/4901979442
- Windows: https://github.com/erlef/setup-beam/actions/runs/3043092227/jobs/4901979281
After:
- Ubuntu: https://github.com/erlef/setup-beam/actions/runs/3059580103/jobs/4937122642
- Windows: https://github.com/erlef/setup-beam/actions/runs/3059580089/jobs/4937122295

Fix setting INSTALL_DIR_FOR_OTP

---

.github/workflows/action.yml
.github/workflows/ubuntu.yml
.github/workflows/update_3rd_party_licenses.yml
.github/workflows/windows.yml
dist/index.js
package-lock.json
package.json

We're getting rid of warnings such as:
* `save-state` will be deprecated
* `set-output` will be deprecated
* Node.js 12 is being deprecated
* ...
while relying on tests to make sure the action still works as it should.
(also closes #146)
| What | Old | New |
| - | - | - |
| `actions/checkout` | v2 | v3 |
| `actions/setup-node` | v2 | v3 |
| `ubuntu` | 18.04 | 20.04 (removed where unusable) |
| `actions/core` | 1.9.1 | 1.10.0 |
| `semver` | 7.3.6 | 7.3.8 |
| `vercel/ncc` | 0.33.4 | 0.34.0 |
| `eslint` | 8.14.0 | 8.25.0 |
| `eslint-plugin-jsx-a11y` | 6.5.1 | 6.6.1 |
| `eslint-plugin-react` | 7.29.0 | 7.31.10 |
| `husky` | 7.0.4 | 8.0.1 |
| `markdownlint` | 0.25.1 | 0.26.2 |
| `prettier` | 2.6.2 | 2.7.1 |
| `yaml-lint` | 1.3.0 | 1.7.0 |
| `yarn` | 1.22.18 | 1.22.19 |

Move away from set-output (while updating all deps)

---

.github/workflows/action.yml
.gitignore
README.md
__tests__/setup-beam.test.js
action.yml
dist/index.js
src/setup-beam.js

This allows using a `.tool-versions` file as per `asdf` constraints.
The `README.md` changes should make the content of the pull request explicit.
---
**Edit**
This is working as expected as can be seen for example repo ([link to `.tool-versions`](https://github.com/paulo-ferraz-oliveira/setup-beam-example/blob/main/.tool-versions)):
- here: [success / versions installed as per `.tool-versions`](https://github.com/paulo-ferraz-oliveira/setup-beam-example/actions/runs/3501999438/jobs/5866104338#step:3:20), 
- here: [error / `version-type =/= strict`](https://github.com/paulo-ferraz-oliveira/setup-beam-example/actions/runs/3501999438/jobs/5866104338#step:4:13)
- and here: [error / colliding inputs](https://github.com/paulo-ferraz-oliveira/setup-beam-example/actions/runs/3501999438/jobs/58661 …

Ease consumption by means of .tool-versions

---

.github/workflows/ubuntu.yml
.github/workflows/windows.yml
dist/index.js
dist/install-elixir.ps1
dist/install-elixir.sh
src/install-elixir.ps1
src/install-elixir.sh
src/setup-beam.js

This adds the mix escripts folder to `PATH`, allowing you to run `mix escript.install hex protobuf --force` and have access to the protobuf generator right away. Making life simpler.
I'm having this as a WIP because I don't program in windows and need to confirm this actually works as intended.

Ease Elixir escripts execution by adding ${HOME}/.mix/escripts to path

---

.github/workflows/ubuntu.yml
README.md
__tests__/setup-beam.test.js

I [recently found](https://github.com/erlef/setup-beam/actions/runs/3648897854/jobs/6162869057#step:5:14) that CI wasn't "failing as it should". I'm opening this PR as a draft to be able to identify the failing elements, then fix potentially them, then convert to "Ready for review".
Also closes #165.

Update versions as to not have CI fail (while fixing "non-failing" CI)

---

.github/workflows/action.yml
.github/workflows/ubuntu.yml
.github/workflows/update_3rd_party_licenses.yml
.github/workflows/windows.yml
action.yml
dist/index.js
src/setup-beam.js

- By providing an input for github tokens with a default users no longer have to pass the github token via their environment across workflows.

Provide an input for github tokens

---

.github/workflows/action.yml
__tests__/setup-beam.test.js

Fix #173.
Let's hope it's as simple as the first commit I'm pushing.

Simulate input `github-token` to fix unit tests

---

.github/elixir-matchers.json
__tests__/problem-matchers.test.js
dist/.github/elixir-matchers.json

Turns out this problem matcher is a little too loose, which causes it to match things it shouldn't. Noticed in [this CI run](https://github.com/btkostner/jumar/actions/runs/4506127234/jobs/7932578120#step:5:153), it will match timestamps in JSON. This can be seen if you run the common `docker/setup-buildx-action@v2` (among others):
```json
{
"nodes": [
{
"name": "builder-ebda29be-8062-4a4a-9e64-efec91d5e3610",
"endpoint": "unix:///var/run/docker.sock",
"status": "running",
"buildkitd-flags": "--allow-insecure-entitlement security.insecure --allow-insecure-entitlement network.host",
"buildkit": "v0.11.5",
"platforms": "linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/386"
}
],
"name": "builder-ebda29be-8062-4a4a-9e64-efec91d5e361",
"driver": "docker-container",
"lastActivity": …
```

Remove Dialyzer-specific problem matcher

---

dist/install-elixir.ps1
dist/install-rebar3.ps1
src/install-elixir.ps1
src/install-rebar3.ps1

In my Windows 11 test environment, using Powershell Core 7.3.4, I get the following message while running similar code to what this github action uses:
```
Installed Elixir version follows
InvalidOperation: C:\Users\vagrant\setup-beam\src\test.ps1:4
Line |
4 |  & "${DIR_FOR_BIN}/bin/elixir" "-v" | Write-Output
|  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| Cannot run a document in the middle of a pipeline: C:\elixir\bin\elixir.
```
Adding `.bat` fixes the issue. This is probably not the root cause of erlef/setup-beam#189, however.

Be explicit about which file (.bat / .cm) is executed in the Windows installation flow

---

.github/workflows/hexpm-mirrors.yml
README.md
__tests__/setup-beam.test.js
action.yml
dist/index.js
dist/install-elixir.ps1
dist/install-elixir.sh
dist/install-otp.sh
src/install-elixir.ps1
src/install-elixir.sh
src/install-otp.sh
src/installer.js
src/setup-beam.js

This is a successor of #156 (see #194 )
Add a new option called `hexpm-mirrors` for one or more hex.pm mirrors.
Default list is `builds.hex.pm`, so behavior is unaffected unless option is
used.
Mirrors will help mitigate recent (and older) issues with official hex.pm mirrors reliability, especially in the context of repositories for which CI performs many queries, some of which may get HTTP errors such as the 502 currently observed.

New option to work with one or more hex.pm mirrors

---

dist/index.js
src/setup-beam.js
test/setup-beam.test.js

Fixes #210.
We need to check that the available `versions` contain the resolved version (which may be the original `spec`).

🐛 Fix OTP version null check

---

dist/index.js
src/installer.js
src/setup-beam.js

I committed a last minute change to `setup-beam`, but this caused a CI issue since the same change doesn't show up in `dist/index.js` :(
There's also a minor change to the code where it was identified before in a different pull request (but since that one's not moving much, I decided to do it here).
**Edit**: I've changed the settings so that at least the static analysis elements are compulsory.

Fix post -main-merge issue

---

.github/workflows/ubuntu.yml
.github/workflows/windows.yml
dist/index.js
src/installer.js
src/setup-beam.js
test/setup-beam.test.js

~Let's keep this open until building OTP 26 on Windows is possible.~
This seems to be in a mergeable state, now. Just need to make sure CI is issue-less.<sup>(1)</sup>
Hopefully fixes #189.
---
<sup>(1)</sup> Yeah, there's some confusion with `master` v. `main` but I'll change everything to main.

Test Erlang/OTP 26 + Elixir 1.14 on top Windows

---

dist/index.js
src/setup-beam.js
test/setup-beam.test.js

This adds support for using source code elixir references in `.tool-versions`, e.g., `elixir ref:v1.15.4`.

Add ref: (version) support to .tool-versions parsing

---

.github/workflows/action.yml
.github/workflows/hexpm-mirrors.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml

We allow GitHub actions pull requests to dispatch the other workflows when version updates are in order.
We also simplify the other conditions to be simply "on push".

Ease pre-pull request fork CI as well as github-actions based dispatch

---

.github/workflows/action.yml
dist/index.js
package-lock.json
package.json

... as per Dependabot ([CVE-2022-25883](https://nvd.nist.gov/vuln/detail/CVE-2022-25883)).

 Bump semver to 7.5.4

---

dist/index.js
src/setup-beam.js
test/setup-beam.test.js

Maybe doing it this way is better, since we don't "break" existing consumption elements, while just adding to already existing exception `-rc-`.
Forcing `version-type: strict`, while explicit, would probably force some installations to use a too-specific Elixir version, so we "fix" what we had to prevent that.
Closes #241.

Add known branch exceptions to version matching

---

package.json

So we don't get keep files we no longer need. I wanted to have pushed this with #246 but I didn't push the local commit 😄

Have `npm run build-dist` _always_ recreate `dist`

---

.github/workflows/ubuntu.yml
.github/workflows/windows.yml
.gitignore
README.md
dist/index.js
package-lock.json
package.json
src/setup-beam.js

This addresses a Windows-specific issue related to a recent change (the target folder which we add to the path after using `tool-cache`) where the tool runs after downloading from cache. Hopefully moving stuff from C: to D: (where the runner keeps e.g. its temp), in Windows, will solve that class of issues. Check the linked bug report for more discussion elements.
I also take this opportunity to do minor changes to the project maintenance files that I'll comment on.
~⚠️ opening as draft, initially, as preparation for merge+release, but to signal waiting for results from linked issue.~
Closes #245.

Move `bin` path, in Windows, from D: to C:

---

dist/index.js
src/setup-beam.js
test/setup-beam.test.js

When using an absolute path like `/tmp/.tool-versions`, the action would look in the file `/$GITHUB_WORKSPACE/tmp/.tool-versions`. This change lets it consider absolute paths as well.

Allow absolute version file paths

---

dist/index.js
src/setup-beam.js

What are we fixing?
If you're `with`ing `"version-file": ".tool-versions"` after you `uses` `"actions/checkout"`, it's likely `rebar3` from `setup-beam` is compiling your project just to output its
version.
This commit prevents that as per
https://github.com/erlang/rebar3/issues/2865#issuecomment-1958608973

Hack around `rebar3` compiling your project to output its `version`

---

CONTRIBUTING.md

I ran into this issue earlier today in a different pull request, and was informed about this requirement. I thought that it would be helpful for other contributors to know that `GITHUB_TOKEN` is a required environment variable for running tests.
Closes #&lt;issue&gt;.

Add GITHUB_TOKEN information to contributing guide

---

.github/workflows/ubuntu.yml
.github/workflows/windows.yml
README.md

I make explicit tests over the newest version of `rebar3` over the newest version of Erlang/OTP. Can't add Elixir to the mix, still, but once we can (1.16, 1.17?) the file is easily updated.

Test over OTP 27 and rebar3 3.23

---

.github/workflows/ubuntu.yml
.github/workflows/windows.yml

This unblocks other pull requests, like:
* https://github.com/erlef/setup-beam/pull/281
* https://github.com/erlef/setup-beam/pull/269

Update CI now that `rebar3` nightly no longer supports OTP 24

---

.github/workflows/ubuntu.yml
.github/workflows/windows.yml

Not that non-RC Elixir 1.17 is release, we use that in our tests.

Test under non-RC Elixir 1.17

---

.markdownlint.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
LICENSE.md
README.md

As per what the title suggests. (if you prefer I can split this into two pull requests)

Tweak `markdownlint` rules and README versioning

---

action.yml

We seemed to have published to the marketplace previously with a description of the action vs the action name. This commit changes the name to simply `setup-beam`.
The link that is out there : `https://github.com/marketplace/actions/setup-erlang-otp-with-optional-elixir-and-mix-and-or-rebar3` 
Additionally, if you search for `setup-beam` or `beam` this will action not come up. We may want to revise the description while we are here.

Fixup action name for the GH marketplace

---

test/setup-beam.test.js

Javascript doesn't care about that, but we do, for maintenance reasons.

Remove input parameter that isn't one (in tests)

---

.github/workflows/windows.yml
test/setup-beam.test.js

1. remove Windows 26.2.5 from tests: (resolved) 26.2.5.2 is [not installing properly](https://github.com/erlang/otp/issues/8666), but the action's CI shouldn't be affected for this.
2. properly simulate `version-type` `strict` when required to not have e.g. `27.0` identify as (recently released) `27.0.1` when that's unexpected.
The motivation for this change was the report in #298, which made me look into why we had issues with version resolution. (issue is not in code, but tests' expectations)

Fix CI (don't use 26.2.5 on Windows; be strict when comparing versions)

---

dist/index.js
src/setup-beam.js

~Add integration test.~ Fix latest
@paulo-ferraz-oliveira, there are some flaky tests or a bug in the version resolution, which is unrelated to my changes.
Closes #297

Fix usage of version `latest` not matching internal elements

---

.github/workflows/action.yml
.github/workflows/ubuntu.yml
dist/index.js
package-lock.json
package.json
src/setup-beam.js
test/setup-beam.test.js

This action uses node 20, which now has the built in `fetch` implementation. We can use that instead of the `@action/http-client` package. This allows us to do our own retry implementation to fix the long standing issue #260.
Closes issue: #260

feat: setup custom retry with builtin node fetch

---

README.md
action.yml
dist/index.js
src/setup-beam.js
test/setup-beam.test.js

Closes #315 .
n.b. I have checked `npm test` and it is returning an exit code of 0, but there is a massive amount of debug output so I could not see any success/fail messages from testing.

Add ability to specify OTP architecture

---

README.md

Fix invalid Markdown in Compatibility section

---

CONTRIBUTING.md
README.md

Fix broken link in README. It fix issue https://github.com/erlef/setup-beam/issues/326.

Fix broken link `CODE_OF_CONDUCT.md`

---

dist/index.js
src/setup-beam.js

We centralise function error output in a function that takes in:
- tool name
- the version
- the URL (or otherwise origin) of the version listing
- an optional list of mirrors
to provide more/better output to the consumer
Closes #301.

Improve output when failing to get a version from "a place"

---

dist/index.js
src/setup-beam.js

Act on a weakness update suggested by CodeQL's scanning: https://github.com/erlef/setup-beam/security/code-scanning/23.
(at most 3 digits for major version)

Match only on what we know should match (versions start with numbers, after OTP-)

---

dist/index.js
src/setup-beam.js

This broke for some consumers, but if we state (as a code warning, and by not having it in the `README.md`) that support is limited, this might not only nudge consumers in the right direction but also "support" those that want to work with deprecated elements.

Add back deprecated runners with warning

---

README.md
dist/index.js
src/setup-beam.js
test/setup-beam.test.js

I'm trying to bring some clarity to https://github.com/erlef/setup-beam/issues/321, with the following in mind:
1. don't break the interface
2. clarify the assumptions in `README.md`
3. test the assumption
Closes #321.

Test for updated doc. on `latest` / ranges / `-rc`

---

.github/workflows/action.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
dist/index.js
src/setup-beam.js
test/setup-beam.test.js

We keep the previous constraint of "user-defined version as 1.19-otp-28" winning over the OTP input, but we now use the `otpVersion` from the installed OTP instead of the user input, which also simplifies code around regular expressions.
* we add `process.env.NODE_ENV` to allow bypassing the initial action run during tests
* instead of calculating `otpVersionMajor` based on input and regex, we make an actual system call (sync) to determine it and use it
* the "bypass if forced" mechanism that was in place stays in place
* per @wojtekmach's input, the Elixir version matching mechanism was changes to start from the detected OTP versions and iterate down until it finds a corresponding Elixir version (this "avoids" OTP `master` / Elixir `main` from becoming Elixir `main` and not …

Fix calculating `-otp-` major for Elixir
